Added command base components. Added commandResult and CommandResultE…
MarisGarrett19/Bookings pull request #28
Opened 2023-05-09 13:37 UTC by MarisGarrett19

…xtensions to provide a consistent result representation and lets the developer check if the command was successful or not and it allows error reporting as well.

2023-05-09 13:42 UTC, stap123 requested changes

2023-05-09 13:42 UTC, stap123 commented on Bookings/Bookings.Shared/Core/Commands/CommandResult.cs
> +    public object? Data { get; set; }
Are you happy to allow any object to be returned from a command?

2023-05-09 13:42 UTC, stap123 commented on Bookings/Bookings.Domain/Core/DomainActionResponse.cs
Are you sure you want to call this DomainActionResponse?

2023-05-10 13:43 UTC, stap123 requested changes

2023-05-10 13:43 UTC, stap123 commented on Bookings/Bookings.Domain/Core/Result.cs
> +    ///     This lets us just return the data as a result from a method and have it automatically turned into a domain action response.
need to update the comment :)

2023-05-10 13:47 UTC, stap123 approved these changes

2023-05-10 13:48 UTC, merged

2023-05-10 13:49 UTC, MarisGarrett19 commented
closes #4